#!/bin/bash
hostnamectl
pstree -a 
service --status-all
ip addr
ss -taulpe
apt list --installed
w
last -xw
ip route | grep default
route -n
nstat
ss -s
iptables -L -n -v
nmap -sV -sS -v
nmap -sV -sU -v 
nmap -p 1-65535 -sV -sS -vv -T1
nmap -p 1-65535 -sV -sU -vv -T1
