#!/bin/bash

hostnamectl
pstree -a 
service --status-all
ip addr
ss -taulpe
apt list --installed
w
last -xw
ip route | grep default
route -n
nstat
ss -s
iptables -L -n -v
nmap -sV -sS -v
nmap -sV -sU -v 
nmap -p 1-65535 -sV -sS -vv -T1
nmap -p 1-65535 -sV -sU -vv -T1

name=script_report
if [[ -e $name.txt ]] ; then
  i=0
  while [[ -e $name-$i.txt ]] ; do
    let i++
  done
  name=$name-$i
fi
touch "$name".txt

hostnamectl > "$name".txt
pstree -a >> "$name".txt
service --status-all >> "$name".txt
ip addr >> "$name".txt
ss -taulpe >> "$name".txt
apt list --installed >> "$name".txt
w >> "$name".txt
last -xw >> "$name".txt
ip route | grep default >> "$name".txt
route -n >> "$name".txt
nstat >> "$name".txt
ss -s >> "$name".txt
iptables -L -n -v >> "$name".txt
nmap -sV -sS -v >> "$name".txt
nmap -sV -sU -v  >> "$name".txt
nmap -p 1-65535 -sV -sS -vv -T1 >> "$name".txt
nmap -p 1-65535 -sV -sU -vv -T1 >> "$name".txt
